
name: Npm Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: 'npm publish'

    environment: npm

    steps:
      - uses: actions/checkout@main

      - name: build
        run: |
          yarn
          yarn build

      - name: 'publish'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          default_branch: 'main'
